# These are supported funding model platforms

github: # [https://github.com/gaurangkumar/]
patreon: # https://www.patreon.com/gaurangkumar
open_collective: https://opencollective.com/gaurangkumar-parmar
ko_fi: https://ko-fi.com/gaurangkumar
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: https://en.liberapay.com/gaurangkumar/
issuehunt: https://issuehunt.io/u/gaurangkumar
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
