# These are supported funding model platforms

github: #[]
patreon: gaurangkumar
open_collective: gaurangkumar-parmar
ko_fi: gaurangkumar
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: gaurangkumar
issuehunt: gaurangkumar
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
