language: php

sudo: false
dist: trusty

php:
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 7.3
        - php: 7.4
    fast_finish: true

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [ "$deps" == "low" ]; then composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-dist; fi
  - php -r "copy('.env.example', '.env');"
  - php jarvis key

script: php jarvis
